#!/bin/bash

for file in $(ls ./git_hooks/hooks/)
do
   	cp git_hooks/hooks/${file} ./.git/hooks/
	chmod +x .git/hooks/${file}
done

(	cd  git_hooks
	if [ ! -d "composer" ]
	then
		mkdir composer
	fi
	cd composer
	composer require --dev "squizlabs/php_codesniffer:<3"
	composer install
)